### ISSUE TITLE
Improve Homekit "powermeter" fan visualization by moving from percentage to a better unit

### ISSUE THREAD

**Issue by datMaffin** [datMaffin/homebridge-tesla-powerwall#25]
Basically upstream https://github.com/leeliu/homebridge-tesla-powerwall/commit/37b1e1a996e09f1d05a25fc4406c08980876353b .

The change was implemented in the past and can therefore be installed via: `sudo npm install -g homebridge-tesla-powerwall@2.0.0-Beta7`.

Commit that implemented the change in this repo: f144a9c23c87a4d70b8ad79eed3e8d06202b6741

Things missing would be (this were the reasons for the revert before the release of 2.0.0):
* [ ] Feedback whether arcdegrees display better than the percentage
* [ ] evaluate the possibility breakage caused by this change (Homekit automation?)
  - Is breakage really something to consider? (the plugin was completely broken for a few months, i.e., nobody should rely too much on this plugin)
* [ ] Update the documentation
* [ ] Should this be implement as a choice/additional service?

**Comment by kimohi** [comment]
I would vote to use the native powerwall values ( as expressed in watts ).   

One interesting sidenote ... it appears you can assign a different unit of measurement in the Powermeter.js .setProps() call for the RotationSpeed characteristic.   If you use 'Watts' instead of 'arcdegrees' as the unit parameter value, the native Apple Home app will display no unit of measurement and just the value ( no degree symbol, no percentage symbol ).   The eve app honors the unit parameter and does display the value unit as 'Watts'.

Siri announces the values as 'Percentage' regardless of the set unit of measurement.

Of course how all of this changes in the future is unknown.

![Screen Shot 2021-05-04 at 9 52 59 AM](https://user-images.githubusercontent.com/83670139/117061976-88928700-acbe-11eb-898c-90288dca91ce.png)
![Screen Shot 2021-05-04 at 9 57 19 AM](https://user-images.githubusercontent.com/83670139/117062425-21290700-acbf-11eb-877b-6f09af5f3d5f.png)

**Comment by leeliu** [comment]
Interesting...I'd rather lose the degree symbol if Watts work. Though with degrees, I get the comma for the thousands separator (ie: 14,493). @kimohi, is that comma missing from your screenshot due to your region settings or is it missing with Watts?

**Comment by leeliu** [comment]
Seems like it's the nature of using Watts as unit. I still think it looks better than degrees (even with a thousands separator).

**Comment by datMaffin** [comment]
There is now `sudo npm install -g homebridge-tesla-powerwall@2.1.0-Beta` that uses "Watts" instead of percentage.

(In addition #3 was implemented.)
